### ISSUE TITLE
[Q] bricolageのサンプル

### ISSUE THREAD

**Issue by hiroyuki-sato** [aamine/bricolage#38]
青木様

佐藤と申します。

## 教えていただきたいこと

* 簡単なもので結構ですので「テーブルを作る」・「データをインサートする」などのサンプルをいただくことはできますでしょうか？
* サンプルにerbや変数の指定例があるとあると助かります。

## ためしたこと

ソース等をみて次のようにテーブルを作ったりコマンドを実行することができました。

### create jobクラス

```
bricolage  --job ./test.job
```

次のようなディレクトリ構成にする。

```
.
|-- config
|   `-- database.yml
`-- subsys
    |-- test.ct
    `-- test.job
```

test.ctにはテーブルの定義を記述する

```sql
create table $dest_table
( x int
, y int
, z int
); 
```

test.jobの書き方

```yaml
class: create      # createクラスを呼び出す
table-def: test.ct # テーブル定義のファイルを指定する
dest-table: test   # 作成するテーブル名変数を指定することができる
drop: true
analyze: true
data-source: hoge # これがYAMLファイルのキーに対応付く
```

database.ymlの書き方

```yaml
hoge:
  type: psql
  host: localhost
  port: 5432
  database: dbname
  username: user
  password: secret
```

### exec job クラスの使い方

```
class: exec
args: ["touch","/tmp/test123"]
```

## やりたいこと

こんなことができればと思っております。自分でコマンド作るよりはこちらのツールを使ってクラスを作る方が簡単そうだと思っております。DBはPostgreSQLです。

* create table XXX inherit ...のようなテーブルを作る。
  * その際CHECK ( date >= DATE '2015-11-01'... AND date < DATE '2015-12-01' )のような変数を埋め込む
* insert into .. select ...のジョブを作る
* トリガの更新を行うためのSQL文を作って実行する
* インデックスの更新を行うためのSQLを作って実行する。

よろしくお願いします。
